name: pokerrunnetwork
description: "PokerRun Network App"
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  remixicon: ^1.4.1
  responsive_sizer: ^3.3.1
  get: ^4.7.3
  custom_check_box: ^0.0.4
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  cloud_firestore: ^6.1.1
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  firebase_auth: ^6.1.3
  paginate_firestore:
  firebase_core: ^4.3.0
  country_currency_pickers: ^3.0.0
  firebase_crashlytics: ^5.0.6
  location: ^8.0.1
  app_settings: ^7.0.0
  image_picker: ^1.2.1
  snackify: ^1.2.4
  youtube_player_flutter: ^9.1.3
  place_picker: ^0.10.0
  flutter_inappwebview: ^6.2.0-beta.2
  firebase_remote_config: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3
  flutter_native_splash:

icons_launcher:
  image_path: "assets/logo/appicon.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#0000FF"
  image: assets/logo/appicon.jpg 
  android: true
  ios: true

  android_12:
    color: "#0000FF"
    image: assets/logo/appicon.jpg 

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/font/
    - assets/icons/
    - assets/background/
    - assets/buttons/menubuttons/
    - assets/buttons/popupbuttons/
  fonts:
    - family: Calibri
      fonts:
        - asset: assets/font/calibri-regular.ttf
        - asset: assets/font/calibri-bold.ttf
          weight: 700
        - asset: assets/font/calibri-italic.ttf
          style: italic
        - asset: assets/font/calibri-bold-italic.ttf
          weight: 700
          style: italic