name: pokerrunnetwork
description: "PokerRun Network App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  remixicon: ^1.4.1
  responsive_sizer: 3.1.1
  get: ^4.7.3
  google_fonts: ^4.0.0
  dotted_border: ^3.1.0
  dropdown_button2: ^2.3.9
  custom_check_box: ^0.0.4
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  firebase_remote_config: ^6.1.0
  # easy_admob_ads_flutter: ^1.0.1
  cached_network_image: ^3.3.1
  timeago: ^3.7.0
  cloud_firestore: ^6.0.3
  intl: ^0.20.2
  flutter_datetime_picker_plus: ^2.2.0
  flutter_easyloading: ^3.0.5
  firebase_auth: ^6.1.1
  paginate_firestore: ^1.0.3+1
  firebase_core: ^4.2.0
  webview_flutter: ^4.13.0
  country_currency_pickers: ^3.0.0
  icons_launcher: ^3.0.3
  firebase_crashlytics:
  location:
  app_settings:
  image_picker:
  snackify:
  place_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

icons_launcher:
  image_path: "assets/logo/appicon.jpg"
  adaptive_background_color: '#0F1552'
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/buttons/menubuttons/
    - assets/buttons/popupbuttons/
    - assets/font/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/font/calibri-regular.ttf
        - asset: assets/font/calibri-bold.ttf
          weight: 700
        - asset: assets/font/calibri-italic.ttf
          style: italic
        - asset: assets/font/calibri-bold-italic.ttf
          weight: 700
          style: italic