name: pokerrunnetwork
description: "PokerRun Network App"
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  remixicon: ^1.4.1
  responsive_sizer: 3.1.1
  get: ^4.7.3
  custom_check_box: ^0.0.4
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0
  firebase_remote_config: ^6.1.0
  cloud_firestore: ^6.0.3
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  firebase_auth: ^6.1.1
  paginate_firestore: ^1.0.3+1
  firebase_core: ^4.2.0
  country_currency_pickers: ^3.0.0
  firebase_crashlytics: ^5.0.6
  location: ^8.0.1
  app_settings: ^7.0.0
  image_picker: ^1.2.1
  snackify: ^1.2.4
  place_picker: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

icons_launcher:
  image_path: "assets/logo/appicon.jpg"
  adaptive_background_color: '#0F1552'
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/background/
    - assets/buttons/menubuttons/
    - assets/buttons/popupbuttons/
    - assets/font/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Calibri
      fonts:
        - asset: assets/font/calibri-regular.ttf
        - asset: assets/font/calibri-bold.ttf
          weight: 700
        - asset: assets/font/calibri-italic.ttf
          style: italic
        - asset: assets/font/calibri-bold-italic.ttf
          weight: 700
          style: italic